### ISSUE TITLE
Uses weak tags

### ISSUE THREAD

**Issue by Y-Less** [AnveSamp/unordered_map#1]
Adding numbers to a map handle, or passing them as a colour makes no sense, so they should be strong tags.

**Comment by AnveSamp** [comment]
For an example?

**Comment by Y-Less** [comment]
`map:` is weak.  I don't know how much more detail you need...

**Comment by AnveSamp** [comment]
Which tag would suit you?

**Comment by YashasSamaga** [comment]
@AnveSamp http://wiki.sa-mp.com/wiki/Scripting:tags#Strong_tags

When I asked you to use templates instead of writing 4 versions, I meant something like this:
```
typedef MapID_t int;

template <typename Key, typename Value>
class IPawnMap
{
public:
	/* common functions */
	size_t size() const { return map.size(); }

	/* virtual functions */
	void emplace(decltype(map)::value_type) = 0;
protected:
	std::unordered_map<Key, Value> map;
	MapID_t id;
};

class PawnMapSS : public IPawnMap<std::string, std::string>
{
public:
	
};
void PawnMapSS::emplace(decltype(map)::value) { /* implementation */ }
```

You can try this:
`std::vector<unique_ptr<IPawnMap>> maps;`

This allows different types of maps to use a common set of map id.

**Comment by AnveSamp** [comment]
Something like this?

template <typename Key, typename Value>
class IPawnMap
{
public:
/* common functions */
size_t size() const { return map.size(); }

/* virtual functions */
protected:
std::unordered_map<Key, Value> map;
MapID_t id;
};

class PawnMapSS : public IPawnMap<std::string, std::string>
{
public:

void emplace(decltype(PawnMapSS::map) value_type);

};

void PawnMapSS::emplace(decltype(PawnMapSS::map) value_type)
{
value_type.emplace("test","lol");
}

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Y-Less** [comment]
`Map:` would be better - it is strong.

**Comment by AnveSamp** [comment]
Tag changed
