### ISSUE TITLE
SA:MP code conventions

### ISSUE THREAD

**Issue by Y-Less** [AnveSamp/unordered_map#2]
Why is `map_new` not `Map_New`, to fit with all other code in SA-MP? The convention for function names has always been camel case, with an underscore for modules.

**Comment by AnveSamp** [comment]
Can this interfere with the use?

**Comment by Y-Less** [comment]
It isn't a technical restriction, just poor practice.

**Comment by AnveSamp** [comment]
I think this is not a big problem?
